<GridLayoutWidget>:
    padding: 20
    spaceing: 20
    cols: 3

    canvas:
        Color:
            rgba: [1, 1, 1, 1]
        Rectangle:
            size: self.size
            pos: self.pos

    Button:
        text: "001"
        size_hint_x: None
        width: '100px'


    Button:
        text: "002"


    Button:
        text: "003"
        size_hint_y: None
        height: '100px'


    Button:
        text: "00A"
