<PageLayoutWidget>:

    anim_kwargs: {'d': 0.1, 't':'linear'}
    page:1
    border: '50dp'
    swip_threshold: 0.1

    Button:
        text: "BTN-00"
        background_color:0.3, 0.3, 0.3, 1

    Button:
        text: "BTN-01"
        background_color:0.9, 0.3, 0.3, 1

    Button:
        text: "BTN-02"
        background_color:0.3, 0.9, 0.3, 1

    Button:
        text: "BTN-03"
        background_color:0.3, 0.3, 0.9, 1

